import io
import re
import math
import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
import numpy as np
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable, KeepTogether
from reportlab.lib.enums import TA_RIGHT, TA_LEFT, TA_CENTER
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Group, Circle
from app.config import settings
from app.services.llm_orchestrator import LLMOrchestrator

logger = logging.getLogger("datova.report_service")


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that automatically adds running headers, running footers,
    and accurate dynamic page counts ('Page X of Y').
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running Top Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(45, 755, "DATOVA AI • EXECUTIVE BUSINESS REPORT")
            self.setFont("Helvetica", 8)
            self.drawRightString(567, 755, "STRICTLY CONFIDENTIAL")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.75)
            self.line(45, 747, 567, 747)

        # Running Footer (all pages)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(45, 45, 567, 45)
        self.setFont("Helvetica", 7.5)
        self.drawString(45, 32, "Generated by Datova Autonomous Intelligence Engine • Dynamic Multi-Sheet Analytics")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(567, 32, page_text)
        self.restoreState()


class ReportService:

    @staticmethod
    def format_cell_value(val: Any) -> str:
        """Helper to format numbers, currencies, dates, and strings cleanly."""
        if val is None or (isinstance(val, float) and math.isnan(val)):
            return "—"
        if isinstance(val, (int, np.integer)):
            return f"{val:,}"
        if isinstance(val, (float, np.floating)):
            if abs(val) >= 1_000_000:
                return f"{val:,.2f}"
            if abs(val) >= 1_000:
                return f"{val:,.1f}"
            if abs(val) < 0.01 and val != 0:
                return f"{val:.4f}"
            return f"{val:,.2f}"
        if isinstance(val, pd.Timestamp):
            return val.strftime("%Y-%m-%d")
        val_str = str(val).strip()
        if len(val_str) > 36:
            return val_str[:33] + "..."
        return val_str

    @staticmethod
    def _extract_architecture_table(dataframes: Dict[str, pd.DataFrame]) -> Dict[str, Any]:
        """Builds a structured metadata table of all uploaded files and sheets."""
        headers = ["Table / Sheet Name", "Total Records", "Column Count", "Key Measures", "Key Dimensions", "Data Density"]
        rows = []
        for name, df in dataframes.items():
            num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
            clean_nums = [c for c in num_cols if not c.lower().endswith("id") and not c.lower().endswith("code")]
            cat_cols = df.select_dtypes(include=["object", "category", "string"]).columns.tolist()
            clean_cats = [c for c in cat_cols if not c.lower().endswith("id")]
            
            non_null_pct = round((df.notnull().sum().sum() / max(df.size, 1)) * 100, 1)
            
            meas_sample = ", ".join(clean_nums[:2]) if clean_nums else "None"
            dim_sample = ", ".join(clean_cats[:2]) if clean_cats else "None"

            rows.append([
                name,
                f"{len(df):,}",
                f"{len(df.columns)}",
                meas_sample,
                dim_sample,
                f"{non_null_pct}%"
            ])

        return {
            "title": "Uploaded Dataset Architecture & Ingestion Profile",
            "subtitle": f"System inventory of {len(dataframes)} processed tabular source(s)",
            "headers": headers,
            "rows": rows,
            "alignments": ["left", "right", "right", "left", "left", "right"],
            "data": [headers, *rows]
        }

    @staticmethod
    def _extract_curated_sample_table(dataframes: Dict[str, pd.DataFrame]) -> Optional[Dict[str, Any]]:
        """Extracts high-signal representative records directly from the primary uploaded file."""
        if not dataframes:
            return None
        primary_name = list(dataframes.keys())[0]
        df = dataframes[primary_name]
        if df.empty:
            return None

        # Prioritize informative columns
        cols = list(df.columns)
        num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = df.select_dtypes(include=["object", "category", "string"]).columns.tolist()
        date_cols = [c for c in df.columns if "date" in c.lower() or "time" in c.lower() or "year" in c.lower()]

        selected_cols = []
        # Primary label / ID
        name_cols = [c for c in cols if any(k in c.lower() for k in ["name", "title", "sku", "product", "employee", "customer", "account", "id"])]
        if name_cols:
            selected_cols.append(name_cols[0])
        # Date column
        if date_cols and date_cols[0] not in selected_cols:
            selected_cols.append(date_cols[0])
        # Up to 2 categorical columns
        for c in cat_cols:
            if c not in selected_cols and len(selected_cols) < 4:
                selected_cols.append(c)
        # Up to 3 numeric columns
        clean_nums = [c for c in num_cols if not c.lower().endswith("id")]
        for c in clean_nums:
            if c not in selected_cols and len(selected_cols) < 7:
                selected_cols.append(c)

        # Fallback if too few
        for c in cols:
            if c not in selected_cols and len(selected_cols) < 6:
                selected_cols.append(c)

        # Select representative rows
        sample_df = df[selected_cols].copy()
        # If numeric metric exists, sort by highest value to show most significant items
        if clean_nums:
            sort_metric = clean_nums[0]
            sample_df = sample_df.sort_values(by=sort_metric, ascending=False).head(6)
        else:
            sample_df = sample_df.head(6)

        headers = list(sample_df.columns)
        rows = []
        alignments = []

        for col in headers:
            if col in num_cols:
                alignments.append("right")
            elif col in date_cols:
                alignments.append("center")
            else:
                alignments.append("left")

        for _, row in sample_df.iterrows():
            formatted_row = [ReportService.format_cell_value(row[c]) for c in headers]
            rows.append(formatted_row)

        return {
            "title": f"Representative Dataset Excerpt: '{primary_name}'",
            "subtitle": f"Top significant observations extracted directly from uploaded records",
            "headers": headers,
            "rows": rows,
            "alignments": alignments,
            "data": [headers, *rows]
        }

    @staticmethod
    def _extract_segment_breakdown_table(dataframes: Dict[str, pd.DataFrame]) -> Optional[Dict[str, Any]]:
        """Calculates dynamic category breakdown and contribution share from the uploaded data."""
        if not dataframes:
            return None
        primary_name = list(dataframes.keys())[0]
        df = dataframes[primary_name]
        
        cat_cols = [c for c in df.select_dtypes(include=["object", "category", "string"]).columns if 2 <= df[c].nunique() <= 35 and not c.lower().endswith("id")]
        num_cols = [c for c in df.select_dtypes(include=[np.number]).columns if not c.lower().endswith("id") and not c.lower().endswith("code")]

        if not cat_cols or not num_cols:
            return None

        cat_col = cat_cols[0]
        num_col = num_cols[0]

        grouped = df.groupby(cat_col)[num_col].agg(["sum", "mean", "count"]).reset_index()
        grouped = grouped.sort_values(by="sum", ascending=False).head(6)
        
        total_sum = df[num_col].sum()
        
        headers = [cat_col.replace("_", " ").title(), "Record Count", f"Total {num_col.replace('_', ' ').title()}", f"Average {num_col.replace('_', ' ').title()}", "Contribution Share"]
        rows = []
        for _, r in grouped.iterrows():
            share_pct = round((r["sum"] / total_sum) * 100, 1) if total_sum > 0 else 0.0
            rows.append([
                str(r[cat_col]),
                f"{int(r['count']):,}",
                ReportService.format_cell_value(r["sum"]),
                ReportService.format_cell_value(r["mean"]),
                f"{share_pct}%"
            ])

        return {
            "title": f"Distribution Breakdown by {cat_col.replace('_', ' ').title()} & {num_col.replace('_', ' ').title()}",
            "subtitle": f"Aggregated performance across prominent segments in '{primary_name}'",
            "headers": headers,
            "rows": rows,
            "alignments": ["left", "right", "right", "right", "right"],
            "data": [headers, *rows]
        }

    @staticmethod
    def _extract_statistical_profile_table(dataframes: Dict[str, pd.DataFrame]) -> Optional[Dict[str, Any]]:
        """Computes statistical moments (mean, median, min, max, std dev) for key numeric columns."""
        if not dataframes:
            return None
        primary_name = list(dataframes.keys())[0]
        df = dataframes[primary_name]
        
        num_cols = [c for c in df.select_dtypes(include=[np.number]).columns if not c.lower().endswith("id") and not c.lower().endswith("code")]
        if not num_cols:
            return None

        headers = ["Numerical Measure", "Mean", "Median", "Min", "Max", "Std Dev", "Valid Coverage"]
        rows = []
        for col in num_cols[:6]:
            series = df[col].dropna()
            if series.empty:
                continue
            mean_val = series.mean()
            median_val = series.median()
            min_val = series.min()
            max_val = series.max()
            std_val = series.std() if len(series) > 1 else 0.0
            coverage_pct = round((len(series) / max(len(df), 1)) * 100, 1)

            rows.append([
                col.replace("_", " ").title(),
                ReportService.format_cell_value(mean_val),
                ReportService.format_cell_value(median_val),
                ReportService.format_cell_value(min_val),
                ReportService.format_cell_value(max_val),
                ReportService.format_cell_value(std_val),
                f"{coverage_pct}%"
            ])

        if not rows:
            return None

        return {
            "title": "Statistical Parameter & Dispersion Matrix",
            "subtitle": f"Parametric distributions calculated across numerical features in '{primary_name}'",
            "headers": headers,
            "rows": rows,
            "alignments": ["left", "right", "right", "right", "right", "right", "right"],
            "data": [headers, *rows]
        }

    @staticmethod
    def _extract_temporal_table(dataframes: Dict[str, pd.DataFrame]) -> Optional[Dict[str, Any]]:
        """Extracts temporal cadence if date columns are present."""
        if not dataframes:
            return None
        primary_name = list(dataframes.keys())[0]
        df = dataframes[primary_name]

        # Find date column
        date_col = None
        for col in df.columns:
            if "date" in col.lower() or "time" in col.lower() or "timestamp" in col.lower():
                try:
                    pd.to_datetime(df[col].dropna().head(10))
                    date_col = col
                    break
                except Exception:
                    continue

        if not date_col:
            return None

        temp_df = df.copy()
        temp_df["_parsed_date"] = pd.to_datetime(temp_df[date_col], errors="coerce")
        temp_df = temp_df.dropna(subset=["_parsed_date"])
        if temp_df.empty:
            return None

        # Choose grouping frequency
        span_days = (temp_df["_parsed_date"].max() - temp_df["_parsed_date"].min()).days
        if span_days > 730:
            temp_df["_period"] = temp_df["_parsed_date"].dt.strftime("%Y")
            period_name = "Year"
        elif span_days > 60:
            temp_df["_period"] = temp_df["_parsed_date"].dt.strftime("%Y-%m")
            period_name = "Month"
        else:
            temp_df["_period"] = temp_df["_parsed_date"].dt.strftime("%Y-%m-%d")
            period_name = "Date"

        num_cols = [c for c in df.select_dtypes(include=[np.number]).columns if not c.lower().endswith("id") and not c.lower().endswith("code")]
        primary_num = num_cols[0] if num_cols else None

        if primary_num:
            grouped = temp_df.groupby("_period").agg(
                volume=("order_id" if "order_id" in temp_df.columns else "_parsed_date", "count"),
                metric_sum=(primary_num, "sum"),
                metric_avg=(primary_num, "mean")
            ).reset_index()
            headers = [period_name, "Observations", f"Total {primary_num.replace('_', ' ').title()}", f"Average {primary_num.replace('_', ' ').title()}"]
        else:
            grouped = temp_df.groupby("_period").size().reset_index(name="volume")
            headers = [period_name, "Observations", "Share of Total"]

        grouped = grouped.sort_values(by="_period", ascending=True).tail(8)

        rows = []
        for _, r in grouped.iterrows():
            if primary_num:
                rows.append([
                    str(r["_period"]),
                    f"{int(r['volume']):,}",
                    ReportService.format_cell_value(r["metric_sum"]),
                    ReportService.format_cell_value(r["metric_avg"])
                ])
            else:
                total_vol = len(temp_df)
                pct = round((r["volume"] / total_vol) * 100, 1) if total_vol > 0 else 0
                rows.append([
                    str(r["_period"]),
                    f"{int(r['volume']):,}",
                    f"{pct}%"
                ])

        return {
            "title": f"Longitudinal Cadence & Temporal Dynamics ({period_name}-over-{period_name})",
            "subtitle": f"Temporal aggregations based on '{date_col}'",
            "headers": headers,
            "rows": rows,
            "alignments": ["left", "right", "right", "right"] if primary_num else ["left", "right", "right"],
            "data": [headers, *rows]
        }

    @staticmethod
    def _generate_kpi_dashboard_chart(kpis: List[Dict[str, Any]], domain: str) -> Optional[Dict[str, Any]]:
        if not kpis:
            return None
        data = []
        for k in kpis[:6]:
            val = k.get("value", 0.0)
            if isinstance(val, (int, float)) and not math.isnan(val):
                data.append({"label": k["display_name"], "value": round(float(val), 2)})
        if not data:
            return None
        
        primary_kpi = kpis[0]
        return {
            "id": "chart_kpi_overview",
            "title": "Primary Operational KPI Benchmarks",
            "subtitle": f"Comparative computed indicators across {domain}",
            "chart_type": "bar",
            "data": data,
            "insight": {
                "headline": f"Core Operational Baseline: {primary_kpi['display_name']} ({primary_kpi.get('formatted_value', '')})",
                "description": f"Baseline performance establishes {primary_kpi['display_name']} as the primary anchor indicator with {len(kpis)} calculated parameters tracked across operations.",
                "impact": "Essential for high-level health tracking and executive benchmarking across quarterly review cycles.",
                "severity": "positive"
            }
        }

    @staticmethod
    def _generate_segment_dashboard_chart(dataframes: Dict[str, pd.DataFrame]) -> Optional[Dict[str, Any]]:
        if not dataframes:
            return None
        primary_name = list(dataframes.keys())[0]
        df = dataframes[primary_name]
        cat_cols = [c for c in df.select_dtypes(include=["object", "category", "string"]).columns if 2 <= df[c].nunique() <= 35 and not c.lower().endswith("id")]
        num_cols = [c for c in df.select_dtypes(include=[np.number]).columns if not c.lower().endswith("id") and not c.lower().endswith("code")]

        if not cat_cols or not num_cols:
            return None

        cat_col = cat_cols[0]
        num_col = num_cols[0]

        grouped = df.groupby(cat_col)[num_col].sum().reset_index()
        grouped = grouped.sort_values(by=num_col, ascending=False).head(7)

        total_sum = grouped[num_col].sum()
        data = []
        for _, r in grouped.iterrows():
            val = float(r[num_col]) if not pd.isna(r[num_col]) else 0.0
            data.append({"label": str(r[cat_col]), "value": round(val, 2)})

        if not data:
            return None

        top_entity = data[0]["label"]
        top_share = round((data[0]["value"] / max(total_sum, 1)) * 100, 1)

        return {
            "id": "chart_segment_distribution",
            "title": f"Distribution Breakdown by {cat_col.replace('_', ' ').title()}",
            "subtitle": f"Aggregated {num_col.replace('_', ' ').title()} across key segments in '{primary_name}'",
            "chart_type": "bar",
            "x_field": cat_col,
            "y_field": num_col,
            "data": data,
            "insight": {
                "headline": f"Segment Dominance: '{top_entity}' Commands {top_share}% of Tracked Volume",
                "description": f"Leader '{top_entity}' accounts for {top_share}% of total {num_col.replace('_', ' ')}. Secondary clusters trail significantly, reflecting concentrated operational reliance.",
                "impact": "Indicates high single-segment leverage that requires operational safeguarding alongside diversification into runner-up tiers.",
                "severity": "high" if top_share > 35 else "medium",
                "metric_highlight": f"{top_share}% Share"
            }
        }

    @staticmethod
    def _generate_temporal_dashboard_chart(dataframes: Dict[str, pd.DataFrame]) -> Optional[Dict[str, Any]]:
        if not dataframes:
            return None
        primary_name = list(dataframes.keys())[0]
        df = dataframes[primary_name]

        date_col = None
        for col in df.columns:
            if any(k in col.lower() for k in ["date", "time", "timestamp", "year", "month"]):
                try:
                    pd.to_datetime(df[col].dropna().head(10))
                    date_col = col
                    break
                except Exception:
                    continue

        if not date_col:
            return None

        temp_df = df.copy()
        temp_df["_parsed_date"] = pd.to_datetime(temp_df[date_col], errors="coerce")
        temp_df = temp_df.dropna(subset=["_parsed_date"])
        if temp_df.empty:
            return None

        span_days = (temp_df["_parsed_date"].max() - temp_df["_parsed_date"].min()).days
        if span_days > 730:
            temp_df["_period"] = temp_df["_parsed_date"].dt.strftime("%Y")
            period_unit = "Year"
        elif span_days > 60:
            temp_df["_period"] = temp_df["_parsed_date"].dt.strftime("%Y-%m")
            period_unit = "Month"
        else:
            temp_df["_period"] = temp_df["_parsed_date"].dt.strftime("%Y-%m-%d")
            period_unit = "Day"

        num_cols = [c for c in df.select_dtypes(include=[np.number]).columns if not c.lower().endswith("id") and not c.lower().endswith("code")]
        primary_num = num_cols[0] if num_cols else None

        if primary_num:
            grouped = temp_df.groupby("_period")[primary_num].sum().reset_index()
        else:
            grouped = temp_df.groupby("_period").size().reset_index(name="count")
            primary_num = "count"

        grouped = grouped.sort_values(by="_period", ascending=True).tail(12)
        data = []
        for _, r in grouped.iterrows():
            val = float(r[primary_num]) if not pd.isna(r[primary_num]) else 0.0
            data.append({"label": str(r["_period"]), "value": round(val, 2)})

        if len(data) < 2:
            return None

        first_val = data[0]["value"]
        last_val = data[-1]["value"]
        peak = max(data, key=lambda d: d["value"])
        pct_change = round(((last_val - first_val) / max(first_val, 1)) * 100, 1)

        return {
            "id": "chart_temporal_cadence",
            "title": f"Longitudinal Velocity & Cadence ({period_unit}-over-{period_unit})",
            "subtitle": f"Temporal progression based on '{date_col}'",
            "chart_type": "line",
            "x_field": date_col,
            "y_field": primary_num,
            "data": data,
            "insight": {
                "headline": f"Temporal Velocity: {pct_change:+}% Progression",
                "description": f"Over the observed periods, observation value moved from {first_val:,} to {last_val:,} with peak volume recorded in {peak['label']} ({peak['value']:,}).",
                "impact": "Validates operational pacing and enables accurate run-rate capacity planning.",
                "severity": "positive" if pct_change > 0 else "high",
                "metric_highlight": f"{pct_change:+}% Shift"
            }
        }

    @staticmethod
    def _generate_dispersion_dashboard_chart(dataframes: Dict[str, pd.DataFrame]) -> Optional[Dict[str, Any]]:
        if not dataframes:
            return None
        primary_name = list(dataframes.keys())[0]
        df = dataframes[primary_name]
        num_cols = [c for c in df.select_dtypes(include=[np.number]).columns if not c.lower().endswith("id") and not c.lower().endswith("code")]
        if not num_cols:
            return None

        col = num_cols[0]
        series = df[col].dropna()
        if series.empty:
            return None

        mean_v = float(series.mean())
        median_v = float(series.median())
        std_v = float(series.std()) if len(series) > 1 else 0.0

        data = [
            {"label": "Median (P50)", "value": round(median_v, 2)},
            {"label": "Mean (Average)", "value": round(mean_v, 2)},
            {"label": "Std Dev (Variance)", "value": round(std_v, 2)},
        ]
        skew_div = round(((mean_v - median_v) / max(median_v, 1)) * 100, 1)

        return {
            "id": "chart_dispersion_profile",
            "title": f"Parametric Variance Profile: '{col.replace('_', ' ').title()}'",
            "subtitle": f"Central tendency vs dispersion in '{primary_name}'",
            "chart_type": "bar",
            "data": data,
            "insight": {
                "headline": f"Distribution Asymmetry: Mean vs Median Divergence of {skew_div:+}%",
                "description": f"The arithmetic mean ({mean_v:,.2f}) diverges from median ({median_v:,.2f}) by {skew_div:+}% with standard deviation of {std_v:,.2f}.",
                "impact": "When mean and median diverge significantly, median targets prevent distorted budget and operational planning.",
                "severity": "medium" if abs(skew_div) > 20 else "low",
                "metric_highlight": f"{skew_div:+}% Skew"
            }
        }

    @staticmethod
    def _generate_anomaly_dashboard_chart(anomalies: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        if not anomalies:
            return None
        data = []
        for a in anomalies[:6]:
            data.append({"label": f"{a['column_name']} ({a['severity'].upper()})", "value": int(a["anomaly_count"])})
        if not data:
            return None

        total_anom = sum(a["anomaly_count"] for a in anomalies)
        return {
            "id": "chart_anomaly_distribution",
            "title": "Outlier Frequency by Feature",
            "subtitle": f"Audit of {total_anom:,} anomalous observations exceeding parametric thresholds",
            "chart_type": "bar",
            "data": data,
            "insight": {
                "headline": f"Outlier Sensitivity Alert: {total_anom:,} Extreme Points Flagged",
                "description": f"Anomalies concentrated in '{anomalies[0]['column_name']}' ({anomalies[0]['anomaly_count']} outliers) warrant operational review.",
                "impact": "Prevents distorted arithmetic reporting and uncovers potential processing or logging defects.",
                "severity": "high"
            }
        }

    @classmethod
    def generate_dynamic_sections(
        cls,
        dataset_name: str,
        domain: str,
        health_info: Dict[str, Any],
        kpis: List[Dict[str, Any]],
        insights: List[Dict[str, Any]],
        anomalies: List[Dict[str, Any]],
        dataframes: Optional[Dict[str, pd.DataFrame]] = None
    ) -> List[Dict[str, Any]]:
        """
        Dynamically designs and formats report sections tailored to the uploaded dataset's
        domain, schema, cardinality, metrics, and relationships.
        Combines narrative synthesis, interactive dashboard charts with meaningful insights,
        and precision-aligned data tables.
        """
        dataframes = dataframes or {}
        sections = []
        order = 0

        total_records = sum(len(df) for df in dataframes.values()) if dataframes else 0
        table_names = list(dataframes.keys())
        primary_name = table_names[0] if table_names else "Primary Table"
        primary_df = dataframes.get(primary_name, pd.DataFrame())

        # Extract structured data components
        arch_table = cls._extract_architecture_table(dataframes) if dataframes else None
        sample_table = cls._extract_curated_sample_table(dataframes)
        segment_table = cls._extract_segment_breakdown_table(dataframes)
        stats_table = cls._extract_statistical_profile_table(dataframes)
        temporal_table = cls._extract_temporal_table(dataframes)

        # Generate visual dashboard charts with meaningful insights
        kpi_chart = cls._generate_kpi_dashboard_chart(kpis, domain)
        segment_chart = cls._generate_segment_dashboard_chart(dataframes)
        temporal_chart = cls._generate_temporal_dashboard_chart(dataframes)
        dispersion_chart = cls._generate_dispersion_dashboard_chart(dataframes)
        anomaly_chart = cls._generate_anomaly_dashboard_chart(anomalies)

        # -------------------------------------------------------------
        # 1. Executive Summary (Domain-Adapted & Plain Language)
        # -------------------------------------------------------------
        kpi_bullets = ", ".join(f"{k['display_name']}: **{k['formatted_value']}**" for k in kpis[:4])
        
        domain_narratives = {
            "Retail & E-Commerce": (
                f"This executive report provides a comprehensive operational evaluation of commercial performance for '{dataset_name}'. "
                f"Drawing from {len(dataframes)} connected data table(s) and {total_records:,} observed customer transactions, "
                f"the business displays steady sales velocity and strong commercial engagement. "
                f"Primary performance benchmarks reflect robust operational volume, led by {kpi_bullets}.\n\n"
                f"Overall data integrity is rated at **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')}), "
                f"confirming that records are well-structured, complete, and dependable for ongoing business planning. "
                f"This verified baseline provides commercial leadership with actionable clarity for inventory allocation, "
                f"merchandising strategy, pricing adjustments, and customer demand forecasting."
            ),
            "Human Resources": (
                f"This workforce intelligence report presents a thorough review of organizational staffing and talent data for '{dataset_name}'. "
                f"Evaluating {total_records:,} personnel records across {len(dataframes)} structural sheet(s), the assessment examines "
                f"departmental headcount distribution, compensation parity, and overall retention stability. "
                f"Core workforce indicators establish a clear baseline, highlighted by {kpi_bullets}.\n\n"
                f"Data hygiene registers at **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')}), "
                f"demonstrating verified consistency across employee records with minimal missing fields. "
                f"This reliable evidence base gives leadership the necessary visibility to evaluate team capacity, "
                f"address resource allocation imbalances, and implement data-informed talent retention and succession plans."
            ),
            "Banking & Finance": (
                f"This financial position and ledger audit provides a clear, structured analysis of transactional activity within '{dataset_name}'. "
                f"Reviewing {total_records:,} monetary records across {len(dataframes)} ledger table(s), the assessment captures "
                f"channel distribution, cash flow velocity, payment methods, and account balance concentration. "
                f"Primary financial indicators demonstrate active capital throughput: {kpi_bullets}.\n\n"
                f"Audit integrity is rated at **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')}), "
                f"confirming reliable reconciliations with thorough ledger documentation. "
                f"These dependable figures provide management with verified clarity for budget tracking, "
                f"liquidity management, financial risk controls, and capital resource planning."
            ),
            "Healthcare & Clinical": (
                f"This clinical performance report provides an organized, detailed evaluation of patient care and treatment records in '{dataset_name}'. "
                f"Covering {total_records:,} clinical observations across {len(dataframes)} table(s), the analysis examines "
                f"patient admission volume, treatment category distributions, diagnostic patterns, and care outcomes. "
                f"Core healthcare indicators reflect consistent clinical activity: {kpi_bullets}.\n\n"
                f"Clinical data completeness registers at **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')}), "
                f"validating high record hygiene and reliable documentation across patient records. "
                f"This solid data foundation supports clinical administrators in monitoring protocol compliance, "
                f"optimizing facility resource allocation, and maintaining high standards of consistent patient care."
            ),
            "Logistics & Supply Chain": (
                f"This supply chain operations briefing delivers an in-depth review of inventory movement, fulfillment, and shipping throughput in '{dataset_name}'. "
                f"Tracking {total_records:,} delivery and warehouse events across {len(dataframes)} operational source(s), the evaluation identifies "
                f"carrier distribution, route transit times, shipment statuses, and fulfillment lead times. "
                f"Primary throughput benchmarks demonstrate active operational flow: {kpi_bullets}.\n\n"
                f"Operational tracking data health is rated at **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')}), "
                f"confirming strong record completeness across shipment stages. "
                f"This verified operational visibility enables logistics managers to proactively resolve transit bottlenecks, "
                f"balance warehouse capacity, and improve delivery reliability."
            ),
            "SaaS & Digital Product": (
                f"This product performance report synthesizes account engagement, subscription tiers, and recurring activity within '{dataset_name}'. "
                f"Analyzing {total_records:,} user and account events across {len(dataframes)} table(s), the assessment highlights "
                f"plan distributions, customer lifecycle milestones, retention patterns, and product utilization trends. "
                f"Core product metrics confirm healthy recurring engagement: {kpi_bullets}.\n\n"
                f"Telemetry integrity registers at **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')}), "
                f"demonstrating high tracking accuracy and consistent event logging. "
                f"These dependable insights provide product leadership with clear guidance for reducing churn, "
                f"refining subscription packaging, and accelerating user lifecycle value."
            )
        }

        default_exec_narrative = (
            f"This executive business report delivers a clear, detailed analytical evaluation of '{dataset_name}'. "
            f"Synthesizing {total_records:,} observed records across {len(dataframes)} table(s) in the {domain} domain, "
            f"the analysis captures macro operational velocity, category distributions, and key performance benchmarks. "
            f"Primary indicators demonstrate solid operational baseline performance: {kpi_bullets}.\n\n"
            f"Overall data quality registers at **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')}), "
            f"confirming that the underlying data is complete, consistent, and dependable for strategic planning. "
            f"This comprehensive synthesis gives leadership verified visibility to evaluate run-rates, allocate resources, "
            f"and make confident, data-informed decisions."
        )

        exec_content = domain_narratives.get(domain, default_exec_narrative)

        sections.append({
            "section_type": "executive_summary",
            "title": f"Executive Summary • {domain}",
            "content": exec_content,
            "order_index": order,
            "charts_included": [kpi_chart] if kpi_chart else [],
            "tables_included": [arch_table] if arch_table else []
        })
        order += 1

        # -------------------------------------------------------------
        # 2. Curated Dataset Excerpt & Primary Entity Snapshot
        # -------------------------------------------------------------
        if sample_table:
            sample_content = (
                f"This section displays a curated snapshot of representative records directly from '{primary_name}', "
                f"providing concrete context for the aggregated metrics throughout this report.\n\n"
                f"Reviewing these individual transactional entries allows stakeholders to verify field structure, "
                f"identifier conventions, date ranges, and numerical distributions. Examining actual rows alongside "
                f"executive summaries provides a tangible, verified connection between raw data inputs and top-level business indicators."
            )
            sections.append({
                "section_type": "dataset_overview",
                "title": "Sample Records & Data Snapshot",
                "content": sample_content,
                "order_index": order,
                "charts_included": [],
                "tables_included": [sample_table]
            })
            order += 1

        # -------------------------------------------------------------
        # 3. Dynamic Key Performance Indicators Matrix
        # -------------------------------------------------------------
        kpi_table_data = [["Metric Name", "Computed Value", "Calculation Base", "Source Column & Table"]]
        kpi_rows = []
        for k in kpis:
            col_ref = f"{k.get('source_table', 'Primary')}.{k.get('source_column')}" if k.get('source_column') else k.get('source_table', 'Primary')
            row_entry = [
                k["display_name"],
                k["formatted_value"],
                k.get("calculation_type", "SUM").upper(),
                col_ref
            ]
            kpi_table_data.append(row_entry)
            kpi_rows.append(row_entry)

        kpi_section_titles = {
            "Retail & E-Commerce": "Key Sales & Revenue Metrics",
            "Human Resources": "Key Workforce & Staffing Metrics",
            "Banking & Finance": "Key Financial & Cash Flow Metrics",
            "Healthcare & Clinical": "Key Patient & Clinical Metrics",
            "Logistics & Supply Chain": "Key Shipping & Fulfillment Metrics",
            "SaaS & Digital Product": "Key Product & Subscription Metrics"
        }

        kpi_narrative = (
            "Key Performance Indicators (KPIs) represent the primary quantitative benchmarks used to monitor business health, "
            "operational volume, and overall momentum. Each metric below was calculated directly from verified fields in your dataset "
            "to establish an objective operational baseline.\n\n"
            "By reviewing these headline figures together, management can quickly evaluate whether current run-rates align with organizational "
            "goals, detect early changes in operating volume, and maintain clear visibility into day-to-day performance."
        )

        sections.append({
            "section_type": "key_metrics",
            "title": kpi_section_titles.get(domain, "Key Performance Indicators (KPIs)"),
            "content": kpi_narrative,
            "order_index": order,
            "charts_included": [kpi_chart] if kpi_chart else [],
            "tables_included": [{
                "title": "KPI Breakdown Table",
                "subtitle": "Computed baselines across key numerical fields",
                "headers": ["Metric Name", "Computed Value", "Calculation Base", "Source Column & Table"],
                "rows": kpi_rows,
                "alignments": ["left", "right", "center", "left"],
                "data": kpi_table_data
            }]
        })
        order += 1

        # -------------------------------------------------------------
        # 4. Domain-Adaptive Segment & Distribution Analysis
        # -------------------------------------------------------------
        if segment_table or segment_chart:
            segment_section_titles = {
                "Retail & E-Commerce": "Product & Category Breakdown",
                "Human Resources": "Department & Headcount Breakdown",
                "Banking & Finance": "Account & Channel Breakdown",
                "Healthcare & Clinical": "Diagnosis & Treatment Breakdown",
                "Logistics & Supply Chain": "Carrier & Route Breakdown",
                "SaaS & Digital Product": "Subscription Tier Breakdown"
            }
            segment_narrative = (
                "Categorical segmentation organizes aggregate numbers across primary groups, departments, channels, or product families "
                "to illustrate where operational activity and value are concentrated.\n\n"
                "In most organizations, a significant share of total output is generated by a core subset of leading categories. "
                "Identifying your top contributors helps leadership focus resources and marketing efforts where they produce the highest return, "
                "while highlighting smaller segments identifies areas that may benefit from process improvements or growth initiatives."
            )
            sections.append({
                "section_type": "segment_analysis",
                "title": segment_section_titles.get(domain, "Category & Segment Breakdown"),
                "content": segment_narrative,
                "order_index": order,
                "charts_included": [segment_chart] if segment_chart else [],
                "tables_included": [segment_table] if segment_table else []
            })
            order += 1

        # -------------------------------------------------------------
        # 5. Statistical Dispersion & Parameter Deep-Dive
        # -------------------------------------------------------------
        if stats_table or dispersion_chart:
            dispersion_narrative = (
                "Analyzing value distribution provides essential insight into the consistency, spread, and predictability of your operational measures.\n\n"
                "Comparing the average (mean) with the middle value (median) clarifies whether recorded numbers are evenly balanced or pulled upward "
                "or downward by unusually high or low entries. Evaluating the minimum, maximum, and standard deviation establishes a realistic range "
                "of expected performance, helping teams plan budgets, allocate staff, and set achievable targets with confidence."
            )
            sections.append({
                "section_type": "trend_analysis",
                "title": "Value Distribution & Typical Spreads",
                "content": dispersion_narrative,
                "order_index": order,
                "charts_included": [dispersion_chart] if dispersion_chart else [],
                "tables_included": [stats_table] if stats_table else []
            })
            order += 1

        # -------------------------------------------------------------
        # 6. Longitudinal Cadence & Temporal Trends (Conditional)
        # -------------------------------------------------------------
        if temporal_table or temporal_chart:
            temporal_narrative = (
                "Tracking metrics across sequential dates and time intervals illustrates the operational rhythm, seasonal cadence, and trajectory of your business.\n\n"
                "Longitudinal analysis helps differentiate temporary short-term spikes from sustained, meaningful trends. "
                "Observing these time-based patterns enables management to anticipate upcoming peak workload cycles, adjust staffing and inventory "
                "ahead of schedule, and accurately evaluate the long-term impact of past operational decisions."
            )
            sections.append({
                "section_type": "trend_analysis",
                "title": "Performance Trends Over Time",
                "content": temporal_narrative,
                "order_index": order,
                "charts_included": [temporal_chart] if temporal_chart else [],
                "tables_included": [temporal_table] if temporal_table else []
            })
            order += 1

        # -------------------------------------------------------------
        # 7. Strategic Analytical Insights
        # -------------------------------------------------------------
        insight_bullets = []
        for ins in insights:
            tag = f"[{ins.get('statement_type', 'CALCULATION').upper()}]"
            insight_bullets.append(
                f"• {tag} **{ins['title']}**: {ins['description']}\n"
                f"  *(Why It Matters: {ins.get('why_it_matters', 'Essential operational benchmark for strategic planning.')})*"
            )

        insight_intro = (
            "The following strategic insights highlight notable empirical patterns and findings discovered across your dataset dimensions. "
            "Each observation connects a verified quantitative pattern with its practical operational significance:\n\n"
        )
        insight_content = insight_intro + "\n\n".join(insight_bullets) if insight_bullets else (
            "No unusual variances or critical anomalies detected across primary dimensions. Operational metrics remain within normal expected ranges."
        )

        sections.append({
            "section_type": "insights",
            "title": "Key Insights & Strategic Findings",
            "content": insight_content,
            "order_index": order,
            "charts_included": [],
            "tables_included": []
        })
        order += 1

        # -------------------------------------------------------------
        # 8. Data Quality, Hygiene & Anomaly Audit
        # -------------------------------------------------------------
        dq_issues = health_info.get("issues", [])
        dq_content = (
            f"A thorough data health audit confirms the completeness, structural integrity, and reliability of the underlying dataset, "
            f"ensuring leadership can make strategic decisions with confidence.\n\n"
            f"**Overall Data Health Score**: **{health_info.get('score', 100)}/100** ({health_info.get('rating', 'Good')})\n"
            f"• **Evaluated Data Points**: {health_info.get('metrics', {}).get('total_cells', 0):,} total cells analyzed across all records.\n"
            f"• **Missing Field Count**: {health_info.get('metrics', {}).get('missing_cells', 0):,} missing entries ({health_info.get('metrics', {}).get('missing_pct', 0)}%).\n"
            f"• **Duplicate Records**: {health_info.get('metrics', {}).get('duplicate_rows', 0):,} duplicated rows detected ({health_info.get('metrics', {}).get('duplicate_pct', 0)}%).\n\n"
            f"High data health ratings indicate that essential fields are well-populated and free from severe structural corruption, "
            f"minimizing reporting distortions and providing reliable numbers for operational planning."
        )
        if dq_issues:
            dq_content += "\n\n**Observed Data Quality Notes**:\n" + "\n".join(
                f"• [{i['severity'].upper()}] **{i['title']}**: {i['description']}" for i in dq_issues[:4]
            )

        anom_table = None
        if anomalies:
            anom_headers = ["Source Table", "Feature Name", "Outlier Count", "Severity", "Impact Explanation"]
            anom_rows = []
            for a in anomalies[:8]:
                anom_rows.append([
                    a["table_name"],
                    a["column_name"],
                    f"{a['anomaly_count']:,}",
                    a["severity"].upper(),
                    a["explanation"]
                ])
            anom_table = {
                "title": "Statistical Anomaly & Outlier Register",
                "subtitle": "Observations exceeding IQR or Z-score distribution thresholds",
                "headers": anom_headers,
                "rows": anom_rows,
                "alignments": ["left", "left", "right", "center", "left"],
                "data": [anom_headers, *anom_rows]
            }

        sections.append({
            "section_type": "data_quality",
            "title": "Data Quality & Health Audit",
            "content": dq_content,
            "order_index": order,
            "charts_included": [anomaly_chart] if anomaly_chart else [],
            "tables_included": [anom_table] if anom_table else []
        })
        order += 1

        # -------------------------------------------------------------
        # 9. Prioritized Strategic Recommendations
        # -------------------------------------------------------------
        recs = [ins.get("recommendation") for ins in insights if ins.get("recommendation")]
        if not recs:
            recs = [
                f"Establish recurring metric monitoring for primary indicators ({', '.join(k['display_name'] for k in kpis[:2])}) to track performance run-rates and identify emerging variations early.",
                f"Maintain data ingestion validation protocols to preserve your data health score above {health_info.get('score', 100)}/100 and safeguard data integrity over time.",
                "Conduct regular category reviews to align operational resourcing with the top-contributing business segments.",
                "Review outlier records periodically to confirm whether high-value observations reflect authentic growth surges or require workflow adjustments."
            ]

        recs_text = (
            "Based on autonomous multi-dimensional analysis of your dataset, the following prioritized action items are recommended "
            "to strengthen operational performance, protect data quality, and capitalize on identified opportunities:\n\n"
            + "\n".join(f"{idx+1}. **{r}**" for idx, r in enumerate(recs[:5]))
        )
        sections.append({
            "section_type": "recommendations",
            "title": "Recommended Next Steps & Action Plan",
            "content": recs_text,
            "order_index": order,
            "charts_included": [],
            "tables_included": []
        })

        return sections

    # Backward compatibility alias
    @classmethod
    def generate_default_sections(
        cls,
        dataset_name: str,
        domain: str,
        health_info: Dict[str, Any],
        kpis: List[Dict[str, Any]],
        insights: List[Dict[str, Any]],
        anomalies: List[Dict[str, Any]],
        dataframes: Optional[Dict[str, pd.DataFrame]] = None
    ) -> List[Dict[str, Any]]:
        return cls.generate_dynamic_sections(
            dataset_name=dataset_name,
            domain=domain,
            health_info=health_info,
            kpis=kpis,
            insights=insights,
            anomalies=anomalies,
            dataframes=dataframes
        )

    # -------------------------------------------------------------
    # PDF Export Engine with Precision Alignment & Dynamic Widths
    # -------------------------------------------------------------
    @staticmethod
    def _clean_markdown_for_pdf(text: str) -> str:
        """Converts Markdown bold, italics, bullets, and special chars to valid ReportLab XML."""
        if not text:
            return ""
        # Escape ampersands not part of XML entity
        cleaned = re.sub(r'&(?!(?:amp|lt|gt|quot|apos);)', '&amp;', text)
        # Escape angle brackets
        cleaned = cleaned.replace("<", "&lt;").replace(">", "&gt;")
        # Bold: **text** -> <b>text</b>
        cleaned = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', cleaned)
        # Italic: only match *text* where * is not internal to identifiers
        cleaned = re.sub(r'(^|\s)\*([^\*]+?)\*(\s|$)', r'\1<i>\2</i>\3', cleaned)
        return cleaned

    @staticmethod
    def _safe_paragraph(text: str, style: ParagraphStyle) -> Paragraph:
        """Safely creates a ReportLab Paragraph, falling back to plain text if malformed markup."""
        try:
            return Paragraph(text, style)
        except Exception:
            plain_text = re.sub(r'<[^>]+>', '', text)
            return Paragraph(plain_text, style)

    @staticmethod
    def _calculate_col_widths(headers: List[str], rows: List[List[Any]], total_width: float = 522.0) -> List[float]:
        """Dynamically computes proportional column widths fitting total printable width exactly."""
        num_cols = len(headers)
        if num_cols == 0:
            return []
        if num_cols == 1:
            return [total_width]

        # Measure length heuristic
        weights = []
        for i in range(num_cols):
            header_len = len(str(headers[i]))
            max_cell_len = max([len(str(r[i])) for r in rows[:10]] + [header_len]) if rows else header_len
            # Apply log/sqrt smoothing to avoid ultra-wide single columns
            weight = math.sqrt(max(max_cell_len, 4))
            weights.append(weight)

        total_weight = sum(weights)
        col_widths = [(w / total_weight) * total_width for w in weights]
        
        # Enforce reasonable minimum width
        min_width = max(38.0, total_width / (num_cols * 2.5))
        for i in range(num_cols):
            if col_widths[i] < min_width:
                col_widths[i] = min_width

        # Renormalize to exact total_width
        current_sum = sum(col_widths)
        col_widths = [(w / current_sum) * total_width for w in col_widths]
        return col_widths

    # -------------------------------------------------------------
    # Vector Graphic Renderers & Dashboard Visualizations for PDF
    # -------------------------------------------------------------
    @classmethod
    def _build_vector_horizontal_bar_chart(
        cls,
        title: str,
        subtitle: str,
        data: List[Dict[str, Any]],
        width: float = 522.0,
        height: float = 125.0
    ) -> Drawing:
        """
        Renders a publication-grade vector horizontal bar chart with proportional
        tracks, percentage contribution shares, and crisp typography.
        """
        d = Drawing(width, height)
        # Background card
        d.add(Rect(0, 0, width, height, rx=4, ry=4, fillColor=colors.HexColor('#F8FAFC'), strokeColor=colors.HexColor('#E2E8F0'), strokeWidth=0.75))
        # Top header banner
        d.add(Rect(0, height - 22, width, 22, rx=4, ry=4, fillColor=colors.HexColor('#0F172A'), strokeColor=None))
        d.add(String(10, height - 15, title.upper(), fontName='Helvetica-Bold', fontSize=7.5, fillColor=colors.white))
        if subtitle:
            d.add(String(width - 10, height - 15, subtitle.upper()[:40], fontName='Helvetica-Bold', fontSize=6.5, fillColor=colors.HexColor('#38BDF8'), textAnchor='end'))

        clean_data = [item for item in data if isinstance(item.get("value"), (int, float)) and not math.isnan(item["value"])]
        if not clean_data:
            d.add(String(width / 2, height / 2 - 5, "No distribution data available", fontName='Helvetica-Oblique', fontSize=8, fillColor=colors.HexColor('#94A3B8'), textAnchor='middle'))
            return d

        display_items = clean_data[:5]
        total_sum = sum(item.get("value", 0) for item in display_items) or 1.0
        max_val = max(item.get("value", 0) for item in display_items) or 1.0
        palette = [
            colors.HexColor('#6366F1'),  # Indigo
            colors.HexColor('#06B6D4'),  # Cyan
            colors.HexColor('#10B981'),  # Emerald
            colors.HexColor('#F59E0B'),  # Amber
            colors.HexColor('#EC4899')   # Pink
        ]

        bar_track_x = 135.0
        bar_track_w = width - bar_track_x - 120.0
        n_items = len(display_items)
        row_height = (height - 30.0) / max(n_items, 1)

        for idx, item in enumerate(display_items):
            y = height - 26.0 - (idx + 1) * row_height + 4.0
            val = float(item.get("value", 0))
            pct = round((val / total_sum) * 100, 1)
            bar_w = max(4.0, (val / max_val) * bar_track_w)
            bar_color = palette[idx % len(palette)]

            lbl = str(item.get("label", ""))
            if len(lbl) > 18:
                lbl = lbl[:16] + ".."
            d.add(String(10, y + 2, lbl, fontName='Helvetica-Bold', fontSize=7, fillColor=colors.HexColor('#1E293B')))

            # Background Track
            d.add(Rect(bar_track_x, y, bar_track_w, 9.0, rx=2.5, ry=2.5, fillColor=colors.HexColor('#E2E8F0'), strokeColor=None))
            # Colored Value Bar
            d.add(Rect(bar_track_x, y, bar_w, 9.0, rx=2.5, ry=2.5, fillColor=bar_color, strokeColor=None))
            # Formatted Value & Share
            val_formatted = cls.format_cell_value(val)
            d.add(String(bar_track_x + bar_track_w + 8.0, y + 2, f"{val_formatted} ({pct}%)", fontName='Helvetica-Bold', fontSize=6.5, fillColor=colors.HexColor('#0F172A')))

        return d

    @classmethod
    def _build_vector_vertical_bar_chart(
        cls,
        title: str,
        subtitle: str,
        data: List[Dict[str, Any]],
        width: float = 522.0,
        height: float = 125.0
    ) -> Drawing:
        """
        Renders a publication-grade vertical column benchmark chart with
        grid baseline, value tags, and category labels.
        """
        d = Drawing(width, height)
        # Background card
        d.add(Rect(0, 0, width, height, rx=4, ry=4, fillColor=colors.HexColor('#F8FAFC'), strokeColor=colors.HexColor('#E2E8F0'), strokeWidth=0.75))
        # Top header banner
        d.add(Rect(0, height - 22, width, 22, rx=4, ry=4, fillColor=colors.HexColor('#0F172A'), strokeColor=None))
        d.add(String(10, height - 15, title.upper(), fontName='Helvetica-Bold', fontSize=7.5, fillColor=colors.white))
        if subtitle:
            d.add(String(width - 10, height - 15, subtitle.upper()[:40], fontName='Helvetica-Bold', fontSize=6.5, fillColor=colors.HexColor('#818CF8'), textAnchor='end'))

        clean_data = [item for item in data if isinstance(item.get("value"), (int, float)) and not math.isnan(item["value"])]
        if not clean_data:
            d.add(String(width / 2, height / 2 - 5, "No benchmark data available", fontName='Helvetica-Oblique', fontSize=8, fillColor=colors.HexColor('#94A3B8'), textAnchor='middle'))
            return d

        display_items = clean_data[:6]
        max_val = max(item.get("value", 0) for item in display_items) or 1.0
        palette = [
            colors.HexColor('#4F46E5'),
            colors.HexColor('#0EA5E9'),
            colors.HexColor('#10B981'),
            colors.HexColor('#F59E0B'),
            colors.HexColor('#8B5CF6'),
            colors.HexColor('#EC4899')
        ]

        chart_x = 32.0
        chart_y = 18.0
        chart_w = width - 64.0
        chart_h = height - 48.0

        # Baseline Axis
        d.add(Line(chart_x, chart_y, chart_x + chart_w, chart_y, strokeColor=colors.HexColor('#CBD5E1'), strokeWidth=1))

        n_items = len(display_items)
        slot_w = chart_w / max(n_items, 1)
        bar_w = min(36.0, slot_w * 0.52)

        for idx, item in enumerate(display_items):
            val = float(item.get("value", 0))
            bar_h = max(3.0, (val / max_val) * (chart_h - 14.0))
            bx = chart_x + idx * slot_w + (slot_w - bar_w) / 2.0
            by = chart_y
            bar_color = palette[idx % len(palette)]

            # Vertical Bar
            d.add(Rect(bx, by, bar_w, bar_h, rx=2.0, ry=2.0, fillColor=bar_color, strokeColor=None))

            # Value label on top
            val_str = cls.format_cell_value(val)
            if len(val_str) > 8:
                val_str = f"{val/1000:.1f}k" if val >= 1000 else val_str[:7]
            d.add(String(bx + bar_w / 2.0, by + bar_h + 2.5, val_str, fontName='Helvetica-Bold', fontSize=6, fillColor=colors.HexColor('#0F172A'), textAnchor='middle'))

            # X Label below
            lbl = str(item.get("label", ""))
            if len(lbl) > 10:
                lbl = lbl[:8] + ".."
            d.add(String(bx + bar_w / 2.0, by - 10.0, lbl, fontName='Helvetica', fontSize=6, fillColor=colors.HexColor('#475569'), textAnchor='middle'))

        return d

    @classmethod
    def _build_kpi_scorecard_grid(cls, kpis: List[Dict[str, Any]], width: float = 522.0) -> Table:
        """
        Constructs a modern 2-column or 3-column KPI scorecards table for the dedicated PDF dashboard.
        """
        if not kpis:
            # Fallback default KPIs
            kpis = [
                {"display_name": "Data Health Index", "formatted_value": "98/100", "calculation_type": "SCORE", "source_column": "Dataset Audit", "impact_summary": "High integrity baseline for analysis."},
                {"display_name": "Total Records", "formatted_value": "Calculated", "calculation_type": "VOLUME", "source_column": "Primary Table", "impact_summary": "Active observations evaluated."}
            ]

        display_kpis = kpis[:4]
        cards = []
        for k in display_kpis:
            name = k.get("display_name", "Metric")
            val = k.get("formatted_value") or cls.format_cell_value(k.get("value", 0))
            calc = (k.get("calculation_type") or "KPI").upper()
            src_tbl = k.get("source_table") or "Primary"
            src_col = k.get("source_column") or "Field"
            src_info = f"Base: {src_tbl}.{src_col}" if src_col else "Calculated Aggregate"
            impact = k.get("impact_summary") or k.get("formula_explanation") or "Core operational indicator."
            if len(impact) > 75:
                impact = impact[:72] + "..."

            card_markup = (
                f"<font size='6.5' color='#4F46E5'><b>[{calc}]</b></font> "
                f"<font size='7.5' color='#0F172A'><b>{name}</b></font><br/>"
                f"<font size='13' color='#0F172A'><b>{val}</b></font><br/>"
                f"<font size='6' color='#64748B'>{src_info}</font><br/>"
                f"<font size='6.5' color='#334155'><i>{impact}</i></font>"
            )
            cards.append(cls._safe_paragraph(card_markup, ParagraphStyle("KpiCardP", fontName="Helvetica", fontSize=7, leading=9.5)))

        # Arrange in 2x2 grid
        rows = []
        if len(cards) >= 4:
            rows = [[cards[0], cards[1]], [cards[2], cards[3]]]
        elif len(cards) == 3:
            rows = [[cards[0], cards[1]], [cards[2], Paragraph("", ParagraphStyle("Blank", fontSize=1))]]
        elif len(cards) == 2:
            rows = [[cards[0], cards[1]]]
        else:
            rows = [[cards[0]]]

        col_w = (width - 6.0) / 2.0
        tbl = Table(rows, colWidths=[col_w, col_w])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (0, 0), 0.75, colors.HexColor("#CBD5E1")),
            ("BOX", (1, 0), (1, 0), 0.75, colors.HexColor("#CBD5E1")),
            ("BOX", (0, 1), (0, -1), 0.75, colors.HexColor("#CBD5E1")),
            ("BOX", (1, 1), (1, -1), 0.75, colors.HexColor("#CBD5E1")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ]))
        return tbl

    @classmethod
    def _build_ai_insight_callout_box(
        cls,
        headline: str,
        description: str,
        impact: str,
        severity: str = "medium",
        width: float = 522.0
    ) -> Table:
        """Constructs an executive AI business insight container with left accent trim."""
        sev_color = "#4F46E5" if severity == "positive" else ("#DC2626" if severity in ["high", "critical"] else "#0284C7")
        markup = (
            f"<b><font size='7.5' color='{sev_color}'>✦ KEY BUSINESS INSIGHT: {cls._clean_markdown_for_pdf(headline)}</font></b><br/>"
            f"<font size='7' color='#1E293B'>{cls._clean_markdown_for_pdf(description)}</font><br/>"
            f"<font size='6.5' color='{sev_color}'><b>Takeaway & Directive:</b> <i>{cls._clean_markdown_for_pdf(impact)}</i></font>"
        )
        p = cls._safe_paragraph(markup, ParagraphStyle("InsightBoxP", fontName="Helvetica", fontSize=7, leading=9.5))
        tbl = Table([[p]], colWidths=[width])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EEF2FF")),
            ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#818CF8")),
            ("LINELEFT", (0, 0), (0, -1), 2.5, colors.HexColor(sev_color)),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ]))
        return tbl

    @classmethod
    def _build_strategic_directives_box(
        cls,
        directives: List[Dict[str, Any]],
        width: float = 522.0
    ) -> Table:
        """Renders AI-generated strategic executive directives."""
        if not directives:
            directives = [
                {"title": "Commercial Growth Allocation", "action": "Focus merchandising and promotional leverage on top-tier contributing segments to compound operational velocity."},
                {"title": "Risk Hedging & Data Hygiene", "action": "Enforce ingestion safeguards around flagged outlier parameters to prevent distorted budget planning."},
                {"title": "Longitudinal Pacing", "action": "Calibrate periodic demand forecasting against identified temporal run rates."}
            ]

        rows = []
        for idx, d in enumerate(directives[:3]):
            title = d.get("title", f"Directive {idx+1}")
            action = d.get("action") or d.get("recommendation") or d.get("description", "")
            badge = f"0{idx+1}"
            markup = (
                f"<b><font size='7.5' color='#0F172A'>[{badge}] {cls._clean_markdown_for_pdf(title)}</font></b><br/>"
                f"<font size='7' color='#334155'>{cls._clean_markdown_for_pdf(action)}</font>"
            )
            rows.append([cls._safe_paragraph(markup, ParagraphStyle(f"DirP{idx}", fontName="Helvetica", fontSize=7, leading=9.5))])

        tbl = Table(rows, colWidths=[width])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
            ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ]))
        return tbl

    @classmethod
    async def synthesize_ai_pdf_briefing(
        cls,
        dataset_name: str,
        domain: str,
        health_score: int,
        kpis: List[Dict[str, Any]],
        insights: List[Dict[str, Any]],
        anomalies: List[Dict[str, Any]],
        dataframes: Optional[Dict[str, pd.DataFrame]] = None
    ) -> Dict[str, Any]:
        """
        Uses the configured AI API key (Gemini / OpenAI / Anthropic / DeepSeek)
        via LLMOrchestrator to synthesize executive briefing insights and directives for the PDF.
        """
        kpi_summary = ", ".join(f"{k.get('display_name')}: {k.get('formatted_value')}" for k in (kpis or [])[:5])
        ins_summary = "; ".join(f"{i.get('title')}: {i.get('description')}" for i in (insights or [])[:3])
        anom_summary = f"{len(anomalies)} outliers detected" if anomalies else "Zero critical anomalies"

        system_prompt = (
            "You are Datova's Principal AI Business Intelligence & Quantitative Strategy Analyst. "
            "Synthesize an elite C-Suite Executive Business Briefing for the provided dataset. "
            "Return structured, concise JSON with bold quantitative metrics and clear actionable directives."
        )

        user_prompt = (
            f"Dataset: '{dataset_name}' in domain '{domain}'. "
            f"Health Score: {health_score}/100. "
            f"Key KPIs: {kpi_summary}. "
            f"Empirical Insights: {ins_summary}. "
            f"Anomaly Profile: {anom_summary}. "
            f"Generate a JSON object with: "
            f"1. 'executive_headline' (string) "
            f"2. 'strategic_takeaway' (string) "
            f"3. 'directives' (array of 3 objects with 'title' and 'action')"
        )

        try:
            raw_json = await LLMOrchestrator.query_llm(system_prompt, user_prompt, response_format_json=True)
            cleaned = LLMOrchestrator._clean_llm_json(raw_json)
            parsed = json.loads(cleaned)
            if isinstance(parsed, dict) and "directives" in parsed:
                return parsed
        except Exception as e:
            logger.warning(f"AI synthesis fallback invoked: {e}")

        # Grounded deterministic fallback
        top_kpi_name = kpis[0].get("display_name", "Primary Indicator") if kpis else "Core Metric"
        top_kpi_val = kpis[0].get("formatted_value", "Optimal") if kpis else "Active"
        return {
            "executive_headline": f"Autonomous Commercial Synthesis • {domain}",
            "strategic_takeaway": f"Evaluation confirms robust operations anchored by {top_kpi_name} ({top_kpi_val}) with high data fidelity.",
            "directives": [
                {"title": "High-Yield Channel Allocation", "action": f"Prioritize operational resourcing around top-performing clusters in {domain}."},
                {"title": "Outlier & Variance Safeguards", "action": "Maintain automated bounds checking to preserve reporting fidelity."},
                {"title": "Strategic Run-Rate Pacing", "action": "Align capacity targets with empirical longitudinal distributions."}
            ]
        }

    @classmethod
    def export_report_pdf(
        cls,
        report_title: str,
        subtitle: str,
        sections: List[Dict[str, Any]],
        kpis: Optional[List[Dict[str, Any]]] = None,
        insights: Optional[List[Dict[str, Any]]] = None,
        anomalies: Optional[List[Dict[str, Any]]] = None,
        dataset_meta: Optional[Dict[str, Any]] = None,
        ai_briefing: Optional[Dict[str, Any]] = None
    ) -> bytes:
        """
        Generates an executive-grade PDF document using ReportLab with:
        - DEDICATED PAGE 1: Key Business Insight Metrics, KPI Scorecards, and Visual Dashboard Charts
        - AI-Synthesized Strategic Findings (powered by LLM API key)
        - Vector-rendered chart graphics and structured insight callouts
        - Multi-page analytical sections with dynamic column width tables and running headers/footers
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=45,
            leftMargin=45,
            topMargin=48,
            bottomMargin=48
        )

        styles = getSampleStyleSheet()

        primary_color = colors.HexColor("#0F172A")    # Deep navy slate
        accent_color = colors.HexColor("#4F46E5")     # Indigo
        text_color = colors.HexColor("#1E293B")       # Slate 800
        muted_color = colors.HexColor("#64748B")      # Slate 500
        brand_bg = colors.HexColor("#F8FAFC")

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=primary_color,
            spaceAfter=2
        )

        subtitle_style = ParagraphStyle(
            "DocSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=muted_color,
            spaceAfter=10
        )

        h1_style = ParagraphStyle(
            "SectionH1",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=accent_color,
            spaceBefore=12,
            spaceAfter=5,
            keepWithNext=True
        )

        dash_header_style = ParagraphStyle(
            "DashSectionHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#0F172A"),
            spaceBefore=6,
            spaceAfter=3,
            keepWithNext=True
        )

        body_style = ParagraphStyle(
            "SectionBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12.5,
            textColor=text_color,
            spaceAfter=6
        )

        bullet_style = ParagraphStyle(
            "SectionBullet",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11.5,
            textColor=text_color,
            leftIndent=10,
            firstLineIndent=-10,
            spaceAfter=3
        )

        tbl_header_left = ParagraphStyle(
            "TblHeaderLeft",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=9.5,
            textColor=colors.white,
            alignment=TA_LEFT
        )

        tbl_header_right = ParagraphStyle(
            "TblHeaderRight",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=9.5,
            textColor=colors.white,
            alignment=TA_RIGHT
        )

        tbl_header_center = ParagraphStyle(
            "TblHeaderCenter",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=9.5,
            textColor=colors.white,
            alignment=TA_CENTER
        )

        tbl_cell_left = ParagraphStyle(
            "TblCellLeft",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=7,
            leading=9.5,
            textColor=text_color,
            alignment=TA_LEFT
        )

        tbl_cell_right = ParagraphStyle(
            "TblCellRight",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=7,
            leading=9.5,
            textColor=text_color,
            alignment=TA_RIGHT
        )

        tbl_cell_center = ParagraphStyle(
            "TblCellCenter",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=7,
            leading=9.5,
            textColor=text_color,
            alignment=TA_CENTER
        )

        story = []

        # Gather context
        meta = dataset_meta or {}
        domain_name = meta.get("domain", "Business Intelligence")
        health_score = meta.get("health_score", 98)
        row_count = meta.get("row_count", 0)

        # Extract KPI metrics if not explicitly passed
        all_kpis = list(kpis) if kpis else []
        if not all_kpis:
            for s in sections:
                for ch in s.get("charts_included", []):
                    if ch.get("chart_type") == "bar" and ch.get("data"):
                        for item in ch["data"][:4]:
                            all_kpis.append({
                                "display_name": item.get("label", "Metric"),
                                "formatted_value": cls.format_cell_value(item.get("value")),
                                "calculation_type": "BENCHMARK",
                                "impact_summary": "Observed empirical measurement."
                            })
                        break
                if all_kpis:
                    break

        # Extract visual charts from sections
        dashboard_charts = []
        for s in sections:
            for ch in s.get("charts_included", []):
                if ch.get("data"):
                    dashboard_charts.append(ch)

        # =========================================================================
        # DEDICATED PAGE 1: KEY BUSINESS INSIGHT METRICS, KPI & VISUAL DASHBOARD
        # =========================================================================
        # 1. Executive Banner & Domain Tags
        banner_tag = f"DATOVA AI • EXECUTIVE BUSINESS INTELLIGENCE DASHBOARD  |  DOMAIN: {domain_name.upper()}"
        story.append(Paragraph(banner_tag, ParagraphStyle("BrandTag", fontName="Helvetica-Bold", fontSize=7.5, textColor=accent_color, spaceAfter=2)))
        story.append(Paragraph(report_title, title_style))
        
        meta_sub = subtitle or f"Autonomous Quantitative Intelligence • Health Score: {health_score}/100 • {row_count:,} Records Analyzed"
        story.append(Paragraph(meta_sub, subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_color, spaceAfter=8))

        # 2. Key Business Insight Metrics & KPI Grid
        story.append(Paragraph("<b>✦ KEY BUSINESS INSIGHT METRIC SCORECARDS & CORE KPIS</b>", dash_header_style))
        kpi_table = cls._build_kpi_scorecard_grid(all_kpis, width=522.0)
        story.append(kpi_table)
        story.append(Spacer(1, 6))

        # 3. Business Insight Visual Dashboard Charts (Vector Graphics)
        story.append(Paragraph("<b>✦ BUSINESS INSIGHT DASHBOARDS & EMPIRICAL VISUALIZATIONS</b>", dash_header_style))
        
        primary_chart = dashboard_charts[0] if dashboard_charts else None
        secondary_chart = dashboard_charts[1] if len(dashboard_charts) > 1 else None

        if primary_chart:
            ch_title = primary_chart.get("title", "Segment Performance Distribution")
            ch_sub = primary_chart.get("subtitle", "")
            ch_data = primary_chart.get("data", [])
            chart_drawing = cls._build_vector_horizontal_bar_chart(ch_title, ch_sub, ch_data, width=522.0, height=105.0)
            story.append(chart_drawing)
            story.append(Spacer(1, 3))

            # Attached AI Insight Box
            insight_info = primary_chart.get("insight")
            if insight_info:
                ins_box = cls._build_ai_insight_callout_box(
                    headline=insight_info.get("headline", "Segment Dominance & Contribution"),
                    description=insight_info.get("description", "Empirical aggregation reveals primary category concentration."),
                    impact=insight_info.get("impact", "Focus operational resourcing on high-performing clusters."),
                    severity=insight_info.get("severity", "positive"),
                    width=522.0
                )
                story.append(ins_box)
                story.append(Spacer(1, 6))

        if secondary_chart:
            ch2_title = secondary_chart.get("title", "Operational Parameter Benchmarks")
            ch2_sub = secondary_chart.get("subtitle", "")
            ch2_data = secondary_chart.get("data", [])
            chart2_drawing = cls._build_vector_vertical_bar_chart(ch2_title, ch2_sub, ch2_data, width=522.0, height=100.0)
            story.append(chart2_drawing)
            story.append(Spacer(1, 3))

            insight2_info = secondary_chart.get("insight")
            if insight2_info:
                ins2_box = cls._build_ai_insight_callout_box(
                    headline=insight2_info.get("headline", "Parametric Benchmarks & Variance"),
                    description=insight2_info.get("description", "Comparative performance demonstrates operational capacity."),
                    impact=insight2_info.get("impact", "Incorporate dispersion thresholds into forward forecast planning."),
                    severity=insight2_info.get("severity", "medium"),
                    width=522.0
                )
                story.append(ins2_box)
                story.append(Spacer(1, 6))

        # 4. AI Strategic Directives & Quantitative Findings
        story.append(Paragraph("<b>✦ AI STRATEGIC DIRECTIVES & QUANTITATIVE FINDINGS (AI REASONING ENGINE)</b>", dash_header_style))
        directives_list = (ai_briefing or {}).get("directives", [])
        if not directives_list and insights:
            directives_list = [{"title": i.get("title", "Insight"), "action": i.get("recommendation") or i.get("description", "")} for i in insights[:3]]
        dir_box = cls._build_strategic_directives_box(directives_list, width=522.0)
        story.append(dir_box)

        # 5. PAGE BREAK TO DEDICATE PAGE 1 AS THE EXECUTIVE DASHBOARD
        story.append(PageBreak())

        # =========================================================================
        # SUBSEQUENT PAGES: MULTI-PAGE DEEP DIVE SECTIONS & PRECISION DATA TABLES
        # =========================================================================
        story.append(Paragraph("DATOVA AUTONOMOUS BI • SECTIONAL DEEP-DIVE & DATA EXTRACTS", ParagraphStyle("BrandTag2", fontName="Helvetica-Bold", fontSize=7.5, textColor=accent_color, spaceAfter=2)))
        story.append(Paragraph(f"Analytical Dossier & Precision Tables • {report_title}", title_style))
        story.append(HRFlowable(width="100%", thickness=1.0, color=colors.HexColor("#CBD5E1"), spaceAfter=10))

        # Render each section
        for idx, sec in enumerate(sections):
            story.append(Paragraph(sec.get("title", f"Section {idx+1}"), h1_style))

            raw_content = sec.get("content", "")
            paragraphs = raw_content.split("\n\n")
            for p_text in paragraphs:
                if not p_text.strip():
                    continue

                lines = p_text.split("\n")
                for line in lines:
                    line_str = line.strip()
                    if not line_str:
                        continue
                    clean_line = cls._clean_markdown_for_pdf(line_str)
                    if line_str.startswith("•") or line_str.startswith("-") or (len(line_str) > 2 and line_str[0].isdigit() and line_str[1] in [".", ")"]):
                        story.append(cls._safe_paragraph(clean_line, bullet_style))
                    else:
                        story.append(cls._safe_paragraph(clean_line, body_style))

            # Charts in deep-dive section
            for ch in sec.get("charts_included", []):
                ch_title = ch.get("title", "Visual Dashboard")
                ch_sub = ch.get("subtitle", "")
                ch_data = ch.get("data", [])
                insight_info = ch.get("insight")

                story.append(Spacer(1, 3))
                # Render vector chart if data exists
                if ch_data:
                    v_chart = cls._build_vector_horizontal_bar_chart(ch_title, ch_sub, ch_data, width=522.0, height=95.0)
                    story.append(v_chart)
                    story.append(Spacer(1, 3))

                # Meaningful Insight Callout in PDF
                if insight_info:
                    hl = insight_info.get("headline", "Key Empirical Finding")
                    desc = insight_info.get("description", "")
                    impact = insight_info.get("impact", "")
                    ins_tbl = cls._build_ai_insight_callout_box(hl, desc, impact, severity=insight_info.get("severity", "medium"), width=522.0)
                    story.append(ins_tbl)
                    story.append(Spacer(1, 4))

            # Tables in deep-dive section
            for tbl in sec.get("tables_included", []):
                headers = tbl.get("headers")
                rows = tbl.get("rows")
                raw_data = tbl.get("data", [])

                if not headers and raw_data:
                    headers = [str(c) for c in raw_data[0]]
                    rows = raw_data[1:]
                elif not rows and raw_data:
                    rows = raw_data[1:] if len(raw_data) > 1 else []

                if not headers or not rows:
                    continue

                alignments = tbl.get("alignments")
                if not alignments or len(alignments) != len(headers):
                    alignments = []
                    for c_idx in range(len(headers)):
                        sample_val = str(rows[0][c_idx]) if rows and c_idx < len(rows[0]) else ""
                        if any(char.isdigit() for char in sample_val) and ("%" in sample_val or "$" in sample_val or sample_val.replace(",", "").replace(".", "").replace("-", "").isdigit()):
                            alignments.append("right")
                        else:
                            alignments.append("left")

                col_widths = cls._calculate_col_widths(headers, rows, total_width=522.0)

                # Format table data
                formatted_table = []
                # Header row
                header_row = []
                for c_idx, h in enumerate(headers):
                    align = alignments[c_idx]
                    h_style = tbl_header_right if align == "right" else (tbl_header_center if align == "center" else tbl_header_left)
                    header_row.append(cls._safe_paragraph(str(h), h_style))
                formatted_table.append(header_row)

                # Data rows (max 15 rows in deep dive table to maintain page balance)
                for r in rows[:15]:
                    data_row = []
                    for c_idx in range(len(headers)):
                        cell_val = str(r[c_idx]) if c_idx < len(r) else ""
                        align = alignments[c_idx]
                        c_style = tbl_cell_right if align == "right" else (tbl_cell_center if align == "center" else tbl_cell_left)
                        data_row.append(cls._safe_paragraph(cls._clean_markdown_for_pdf(cell_val), c_style))
                    formatted_table.append(data_row)

                # Table title if present
                tbl_title = tbl.get("title")
                if tbl_title:
                    story.append(cls._safe_paragraph(f"<b>{tbl_title}</b>", ParagraphStyle("TblTitle", fontName="Helvetica-Bold", fontSize=8, textColor=primary_color, spaceBefore=5, spaceAfter=2)))

                pdf_table = Table(formatted_table, colWidths=col_widths, repeatRows=1)
                t_style = [
                    ("BACKGROUND", (0, 0), (-1, 0), primary_color),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ("LINEBELOW", (0, 0), (-1, 0), 1.2, accent_color),
                    ("LINEBELOW", (0, 1), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ]
                for r_i in range(1, len(formatted_table)):
                    if r_i % 2 == 0:
                        t_style.append(("BACKGROUND", (0, r_i), (-1, r_i), brand_bg))

                pdf_table.setStyle(TableStyle(t_style))
                story.append(Spacer(1, 3))
                story.append(pdf_table)
                story.append(Spacer(1, 6))

            story.append(Spacer(1, 6))

        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def export_report_excel(report_title: str, sections: List[Dict[str, Any]], dataframes: Dict[str, pd.DataFrame]) -> bytes:
        """
        Exports the report sections, structured tables, and raw dataset tables into a multi-tab Excel workbook.
        """
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
            # 1. Executive Summary Tab
            summary_rows = []
            for sec in sections:
                summary_rows.append({
                    "Section Title": sec.get("title"),
                    "Narrative Content": sec.get("content")
                })
            pd.DataFrame(summary_rows).to_excel(writer, sheet_name="Executive Summary", index=False)

            # 2. Structured Report Tables Tab
            for sec in sections:
                for tbl in sec.get("tables_included", []):
                    t_title = tbl.get("title", "Table")
                    headers = tbl.get("headers")
                    rows = tbl.get("rows")
                    if headers and rows:
                        df_tbl = pd.DataFrame(rows, columns=headers)
                        safe_sheet = re.sub(r'[\\/*?:\[\]]', '_', t_title)[:30]
                        df_tbl.to_excel(writer, sheet_name=safe_sheet, index=False)

            # 3. Raw Data Tabs (up to 1,000 rows each)
            for tbl_name, df in dataframes.items():
                safe_name = re.sub(r'[\\/*?:\[\]]', '_', tbl_name)[:30]
                df.head(1000).to_excel(writer, sheet_name=safe_name, index=False)

        buffer.seek(0)
        return buffer.getvalue()
